
from flask import Flask, jsonify
import os

app = Flask(__name__)

# Define where to save files
MEDIA_FOLDER = '/path/to/media/folder'
os.makedirs(MEDIA_FOLDER, exist_ok=True)

@app.route('/generate-file')
def generate_file():
    # Create your dynamic content
    filename = 'dynamic_file.txt'
    file_path = os.path.join(MEDIA_FOLDER, filename)

    with open(file_path, 'w') as f:
        f.write('This is dynamic content generated by Flask.')

    # Return the URL where Nginx can serve the file
    file_url = f'/media/{filename}'
    return jsonify({'file_url': file_url})

if __name__ == '__main__':
    app.run()
