
import logging
import logging.config
from configparser import ConfigParser

# Load the configuration from an INI file
config = ConfigParser()
config.read('logging_config.ini')

logging.config.fileConfig('logging_config.ini')

# Now you can get the logger for sqlalchemy.engine
logger = logging.getLogger('sqlalchemy.engine')

# Example usage of the logger
logger.info('This is an info message generated by SQLAlchemy.')
logger.debug('This debug message will not show without DEBUG level set.')
